runs new \
--path="neurips/long-jump/no-roll/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer"

echo waiting
read 
runs new \
--path="neurips/long-jump/no-roll-or-scan/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"100\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll-or-scan/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"100\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll-or-scan/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"100\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll-or-scan/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"100\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-roll-or-scan/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-roll --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"100\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.7\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" 

echo waiting
read 

runs new \
--path="neurips/long-jump/no-scan/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-scan/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-scan/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-scan/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/no-scan/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-scan --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer"

echo waiting
read

runs new \
--path="neurips/long-jump/transformer/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --transformer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\" --load-path=/home/ethanbro/tmux-script/checkpoints/transformer/0/checkpoint.pt " \
--path="neurips/long-jump/transformer/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --transformer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\" --load-path=/home/ethanbro/tmux-script/checkpoints/transformer/1/checkpoint.pt " \
--path="neurips/long-jump/transformer/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --transformer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\" --load-path=/home/ethanbro/tmux-script/checkpoints/transformer/2/checkpoint.pt " \
--path="neurips/long-jump/transformer/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --transformer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\" --load-path=/home/ethanbro/tmux-script/checkpoints/transformer/3/checkpoint.pt " \
--path="neurips/long-jump/transformer/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --transformer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"z\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\" --load-path=/home/ethanbro/tmux-script/checkpoints/transformer/4/checkpoint.pt " 



echo 'waiting'
read 



runs new \
--path="neurips/long-jump/no-pointer/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-pointer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix no_pointer" \
--path="neurips/long-jump/no-pointer/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-pointer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix no_pointer" \
--path="neurips/long-jump/no-pointer/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-pointer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix no_pointer" \
--path="neurips/long-jump/no-pointer/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-pointer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix no_pointer" \
--path="neurips/long-jump/no-pointer/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --no-pointer --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"128\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.4\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"9\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.6\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix no_pointer"


echo 'waiting'
read 


runs new \
--path="neurips/long-jump/ours/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="update checkpoint" \
--path="neurips/long-jump/ours/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="update checkpoint" \
--path="neurips/long-jump/ours/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="update checkpoint" \
--path="neurips/long-jump/ours/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="update checkpoint" \
--path="neurips/long-jump/ours/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"32\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"32\" --gate-stride=\"2\" --hidden-size=\"128\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"50\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"64\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="update checkpoint"



echo 'waiting'
read 


runs new \
--path="neurips/long-jump/olsk/0" \
--command="python ppo/control_flow/main.py                                       --gridworld --olsk --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"0\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/olsk/1" \
--command="python ppo/control_flow/main.py                                       --gridworld --olsk --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"1\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/olsk/2" \
--command="python ppo/control_flow/main.py                                       --gridworld --olsk --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"2\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/olsk/3" \
--command="python ppo/control_flow/main.py                                       --gridworld --olsk --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"3\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer" \
--path="neurips/long-jump/olsk/4" \
--command="python ppo/control_flow/main.py                                       --gridworld --olsk --control-flow-types \"Subtask\" \"If\" \"Else\" \"While\" --conv-hidden-size=\"64\" --critic-type=\"h1\" --entropy-coef=\"0.015\" --eval-interval=\"100\" --eval-steps=\"500\" --failure-buffer-size=\"500\" --flip-prob=\"0.5\" --gate-coef=\"0.01\" --gate-conv-kernel-size=\"2\" --gate-hidden-size=\"16\" --gate-stride=\"2\" --hidden-size=\"64\" --hidden2=\"32\" --kernel-size=\"2\" --learning-rate=\"0.0025\" --lower-embed-size=\"64\" --lower-level-config=\"checkpoint/lower.json\" --lower-level-load-path=\"checkpoint/lower.pt\" --max-eval-lines=\"50\" --max-failure-sample-prob=\"0.3\" --max-lines=\"10\" --max-loops=\"3\" --max-nesting-depth=\"1\" --max-while-loops=\"10\" --max-world-resamples=\"20\" --min-eval-lines=\"10\" --min-lines=\"1\" --no-op-coef=\"0\" --no-op-limit=\"30\" --num-batch=\"1\" --num-conv-layers=\"0\" --num-edges=\"2\" --num-encoding-layers=\"0\" --num-layers=\"0\" --num-processes=\"150\" --num-steps=\"25\" --ppo-epoch=\"2\" --reject-while-prob=\"0.5\" --seed=\"4\" --stride=\"2\" --task-embed-size=\"32\" --term-on \"mine\" \"sell\" --time-to-waste=\"0\" --world-size=\"6\"  " \
--description="fix olsk and no_pointer"

