wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
assimilator_prob:
  desc: null
  value: 0.7
conv_hidden_size:
  desc: null
  value: 100
entropy_coef:
  desc: null
  value: 0.015
hidden_size:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0025
lower_embed_size:
  desc: null
  value: 75
next_actions_embed_size:
  desc: null
  value: 75
num_batch:
  desc: null
  value: 2
num_initial_buildings:
  desc: null
  value: 0
num_processes:
  desc: null
  value: 30
ppo_epoch:
  desc: null
  value: 5
time_per_line:
  desc: null
  value: 20
train_steps:
  desc: null
  value: 35
