#! /usr/bin/env zsh

task=$(echo $2 | sed -r 's/.runs\/log-dir\///g')
cmd=$(runs lookup command $task --porcelain)
eval $(echo "$cmd $1" |  sed -r 's/--log-dir=(\S*)/--load-path=\1\/checkpoint.pt/g'| sed -r 's/num-processes=(\S*)/num-processes=1/g')
